package reptile

import (
	"github.com/chromedp/chromedp/kb"
)

func GetKbKey(key string) string {
	switch key {
	case "\b":
		return kb.Backspace
	case "\t":
		return kb.Tab
	case "\r":
		return kb.Enter
	case "\u001b":
		return kb.Escape
	case "'":
		return kb.Quote
	case "\\":
		return kb.Backslash
	case "\u007f":
		return kb.Delete
	case "\u0102":
		return kb.Alt
	case "\u0104":
		return kb.CapsLock
	case "\u0105":
		return kb.Control
	case "\u0106":
		return kb.Fn
	case "\u0107":
		return kb.FnLock
	case "\u0108":
		return kb.Hyper
	case "\u0109":
		return kb.Meta
	case "\u010a":
		return kb.NumLock
	case "\u010c":
		return kb.ScrollLock
	case "\u010d":
		return kb.Shift
	case "\u010e":
		return kb.Super
	case "\u0301":
		return kb.ArrowDown
	case "\u0302":
		return kb.ArrowLeft
	case "\u0303":
		return kb.ArrowRight
	case "\u0304":
		return kb.ArrowUp
	case "\u0305":
		return kb.End
	case "\u0306":
		return kb.Home
	case "\u0307":
		return kb.PageDown
	case "\u0308":
		return kb.PageUp
	case "\u0401":
		return kb.Clear
	case "\u0402":
		return kb.Copy
	case "\u0404":
		return kb.Cut
	case "\u0407":
		return kb.Insert
	case "\u0408":
		return kb.Paste
	case "\u0409":
		return kb.Redo
	case "\u040a":
		return kb.Undo
	case "\u0502":
		return kb.Again
	case "\u0504":
		return kb.Cancel
	case "\u0505":
		return kb.ContextMenu
	case "\u0507":
		return kb.Find
	case "\u0508":
		return kb.Help
	case "\u0509":
		return kb.Pause
	case "\u050b":
		return kb.Props
	case "\u050c":
		return kb.Select
	case "\u050d":
		return kb.ZoomIn
	case "\u050e":
		return kb.ZoomOut
	case "\u0601":
		return kb.BrightnessDown
	case "\u0602":
		return kb.BrightnessUp
	case "\u0604":
		return kb.Eject
	case "\u0605":
		return kb.LogOff
	case "\u0606":
		return kb.Power
	case "\u0608":
		return kb.PrintScreen
	case "\u060b":
		return kb.WakeUp
	case "\u0705":
		return kb.Convert
	case "\u070b":
		return kb.ModeChange
	case "\u070d":
		return kb.NonConvert
	case "\u0711":
		return kb.HangulMode
	case "\u0712":
		return kb.HanjaMode
	case "\u0716":
		return kb.Hiragana
	case "\u0718":
		return kb.KanaMode
	case "\u071a":
		return kb.Katakana
	case "\u071d":
		return kb.ZenkakuHankaku
	case "\u0801":
		return kb.F1
	case "\u0802":
		return kb.F2
	case "\u0803":
		return kb.F3
	case "\u0804":
		return kb.F4
	case "\u0805":
		return kb.F5
	default:
		return key
	}
}
